sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: jdbc:mysql://localhost:3316
    host: localhost
    port: 3316
    database: sky_take_out
    username: root
    password: ''